micronaut:
  server:
    port: 9090

datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    schema-generate: CREATE_DROP
    dialect: POSTGRES
    jdbc-url: jdbc:postgresql://localhost:5432/perobobbot
    username: admin
    password: password

curator:
  client:
    connect-string: localhost:2181
  discovery:
    host: localhost
    port: 9090
    ssl-port: -1


perobobbot:
  data:
    dbPassPhrase: pass-phrase