micronaut:
  application:
    name: Perobobbot Data
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

curator:
  enabled: true
  client:
    prefix: perobobbot/discovery
  discovery:
    serviceId: perobobbot

client:
  secret: ${CLIENT_SECRET}

jpa.default.properties.hibernate.hbm2ddl.auto: update


netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages: perobobbot.service.jpa.domain
