micronaut:
  server:
    port: 9090
    ssl:
      port: 9444
      build-self-signed: true
      enabled: true

datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    schema-generate: CREATE_DROP
    dialect: POSTGRES
    jdbc-url: jdbc:postgresql://localhost:5432/perobobbot
    username: admin
    password: password

curator:
  client:
    connect-string: localhost:2181
  discovery:
    host: localhost
    port: 9090
    ssl-port: -1


perobobbot:
  data:
    user: Perobobbot
    dbPassPhrase: pass-phrase
  plugin:
    folder: /home/perococco/Perobobbot/plugins
  eventsub:
    secret: 8Aasd*()AS(D23{@!ASFD987AS@!&*ASC
    backupMessages: true
    callbackURL: https://femtoparsec.net/bot/callback/twitch
